### ISSUE TITLE
Noise reduction in the VNA output signal

### ISSUE THREAD

**Issue by amosepehr** [jankae/VNA#3]
Hello
Thanks for your design, I wanted a guide. I would appreciate it if you could help me.
I need a VNA that has minimal noise effects on the output signal. Is it possible to increase the input signal amplitude to +10 dBm in your design instead of -25 dBm? And measure this +25 dBm at the output? If you have a solution to this challenge, please help me.
With best regards.

**Comment by jankae** [comment]
Hi, I am a bit lost here. When you say output, do you mean the output of the VNA or the output of the DUT (which would be the input of the VNA)?
I also can not follow your dBm numbers:

>  increase the input signal amplitude to +10 dBm

Do you mean the signal level as generated by the VNA? No, you can not go as high as +10 dBm.

>  instead of -25 dBm?

No clue what you mean. My design has no power level which is limited to -25 dBm.

> And measure this +25 dBm at the output?

And now it is +25 dBm instead of -25 dBm? Where is that coming from? And no, you can not measure +25 dBm with the LibreVNA. Linear measurements are possible up to about 0 dBm, if you go above that, you will no longer be able to make accurate measurements. And if you go way above that, you will damage the input stage of the LibreVNA. Do not apply +25 dBm directly to either port!

I think you will need to explain a bit more about your measurement setup here, otherwise I can not help you. Unless you are talking about an actual redesign of the VNA, the answer will be most likely "use an external amplifier and de-embed it".

**Comment by jankae** [comment]
Also: I just noticed that this is not the repository of the LibreVNA. This repository contains an old prototype of which only a single unit was ever assembled. See [here ](https://github.com/jankae/LibreVNA)for the LibreVNA repository.
I'll go ahead and close this because there will be no further development here. Feel free to open a new issue in the LibreVNA repository.
